# Generated by Django 6.0.3 on 2026-03-31 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieOeuf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('duree_incubation_jours', models.IntegerField(help_text="Nombre de jours pour l'éclosion")),
                ('temperature_recommandee', models.DecimalField(blank=True, decimal_places=2, default=37.5, help_text='Température en °C', max_digits=4, null=True)),
                ('humidite_recommandee', models.IntegerField(blank=True, default=55, help_text='Humidité en %', null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "Catégories d'œufs",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('telephone_2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_depôt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure du dépôt')),
                ('quantite_oeufs', models.IntegerField(default=0)),
                ('quantite_eclos', models.IntegerField(default=0)),
                ('montant_percu', models.DecimalField(decimal_places=2, default=0, help_text='Montant payé par le client', max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, help_text='Prix par œuf', max_digits=6)),
                ('statut', models.CharField(choices=[('en_cours', 'En incubation'), ('eclos', 'Éclos'), ('echec', 'Échec'), ('annule', 'Annulé')], default='en_cours', max_length=20)),
                ('date_eclosion_prevue', models.DateField(blank=True, null=True)),
                ('remarque', models.TextField(blank=True, help_text='Remarques sur les œufs ou le dépôt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='couveuse_app.client')),
            ],
            options={
                'verbose_name_plural': 'Dépôts',
                'ordering': ['-date_heure_depôt'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('j_7', 'J-7'), ('j_3', 'J-3'), ('j_1', 'J-1'), ('jour_j', 'Jour J'), ('retard', 'Retard')], max_length=10)),
                ('message', models.TextField()),
                ('date_prevue', models.DateTimeField()),
                ('date_envoyee', models.DateTimeField(blank=True, null=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couveuse_app.depot')),
            ],
            options={
                'ordering': ['-date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='couveuse_app.categorieoeuf')),
            ],
            options={
                'verbose_name_plural': 'Races',
                'ordering': ['categorie', 'nom'],
                'unique_together': {('categorie', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='depot',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='couveuse_app.race'),
        ),
    ]
