# Generated by Django 6.0.3 on 2026-04-03 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couveuse_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Numéro unique de la palette', unique=True)),
                ('est_disponible', models.BooleanField(default=True, help_text='True si la palette est libre, False si elle est occupée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Palettes',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='depot',
            name='palette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots', to='couveuse_app.palette'),
        ),
    ]
