# Generated by Django 6.0.3 on 2026-04-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couveuse_app', '0002_palette_depot_palette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palette',
            name='est_disponible',
        ),
    ]
