# Generated by Django 6.0.3 on 2026-04-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couveuse_app', '0003_remove_palette_est_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='alerte_perso_active',
            field=models.BooleanField(default=False, verbose_name='Alerte personnalisée active'),
        ),
        migrations.AddField(
            model_name='depot',
            name='alerte_perso_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date et heure de l'alerte personnalisée"),
        ),
        migrations.AddField(
            model_name='depot',
            name='alerte_perso_message',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Message de l'alerte personnalisée"),
        ),
    ]
