# Generated by Django 6.0.3 on 2026-04-04 01:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couveuse_app', '0004_depot_alerte_perso_active_depot_alerte_perso_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], help_text='Type: Entrée ou Sortie', max_length=10)),
                ('categorie', models.CharField(choices=[('depot_client', 'Dépôt client'), ('eclosion', 'Éclosion payée'), ('autre_entree', 'Autre entrée'), ('achat_materiel', 'Achat matériel'), ('electricite', 'Électricité'), ('eau', 'Eau'), ('salaire', 'Salaire'), ('maintenance', 'Maintenance'), ('transport', 'Transport'), ('autre_sortie', 'Autre sortie')], help_text='Catégorie de la transaction', max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant en FCFA', max_digits=12)),
                ('description', models.TextField(blank=True, help_text='Description détaillée')),
                ('date_transaction', models.DateField(default=django.utils.timezone.now, help_text='Date de la transaction')),
                ('reference', models.CharField(blank=True, help_text='Référence ou numéro de reçu', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('client', models.ForeignKey(blank=True, help_text='Client associé (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='couveuse_app.client')),
                ('depot', models.ForeignKey(blank=True, help_text='Dépôt associé (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='couveuse_app.depot')),
            ],
            options={
                'verbose_name': 'Transaction de caisse',
                'verbose_name_plural': 'Transactions de caisse',
                'ordering': ['-date_transaction', '-created_at'],
            },
        ),
    ]
