# Generated by Django 6.0.3 on 2026-04-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couveuse_app', '0005_transactioncaisse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(default='Ma Couveuse', max_length=100, verbose_name="Nom de l'entreprise")),
                ('adresse_entreprise', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone_entreprise', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email_entreprise', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('code_pin', models.CharField(blank=True, help_text='Code pour protéger les actions sensibles', max_length=4, verbose_name='Code PIN (4 chiffres)')),
                ('code_pin_actif', models.BooleanField(default=False, verbose_name='Activer le code PIN')),
                ('son_jour_j', models.CharField(blank=True, default='/static/sounds/alarm_critical.mp3', max_length=255, verbose_name='Son Jour J (éclosion)')),
                ('son_j_1', models.CharField(blank=True, default='/static/sounds/alarm_warning.mp3', max_length=255, verbose_name='Son J-1')),
                ('son_j_3', models.CharField(blank=True, default='/static/sounds/alarm_info.mp3', max_length=255, verbose_name='Son J-3')),
                ('son_perso', models.CharField(blank=True, default='/static/sounds/alarm_perso.mp3', max_length=255, verbose_name='Son alerte personnalisée')),
                ('notifications_actives', models.BooleanField(default=True, verbose_name='Notifications navigateur')),
                ('son_actif', models.BooleanField(default=True, verbose_name="Sons d'alerte")),
                ('repetition_alarme', models.IntegerField(default=3, verbose_name="Nombre de répétitions d'alarme")),
                ('temperature_defaut', models.DecimalField(decimal_places=2, default=37.5, max_digits=4, verbose_name='Température par défaut (°C)')),
                ('humidite_defaut', models.IntegerField(default=55, verbose_name='Humidité par défaut (%)')),
                ('theme', models.CharField(default='light', max_length=20, verbose_name='Thème')),
                ('langue', models.CharField(default='fr', max_length=5, verbose_name='Langue')),
                ('sauvegarde_auto', models.BooleanField(default=True, verbose_name='Sauvegarde automatique')),
                ('frequence_sauvegarde', models.IntegerField(default=7, verbose_name='Fréquence de sauvegarde (jours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
            },
        ),
    ]
