# Generated by Django 6.0.3 on 2026-04-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couveuse_app', '0006_parametre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametre',
            name='nom_entreprise',
            field=models.CharField(blank=True, default='Ma Couveuse', max_length=100, verbose_name="Nom de l'entreprise"),
        ),
    ]
