# Generated by Django 6.0.4 on 2026-04-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couveuse_app', '0007_add_blank_to_nom_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametre',
            name='son_j_1',
            field=models.CharField(blank=True, default='/static/audio/alarm_warning.mp3', max_length=255, verbose_name='Son J-1'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='son_j_3',
            field=models.CharField(blank=True, default='/static/audio/alarm_info.mp3', max_length=255, verbose_name='Son J-3'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='son_jour_j',
            field=models.CharField(blank=True, default='/static/audio/alarm_critical.mp3', max_length=255, verbose_name='Son Jour J (éclosion)'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='son_perso',
            field=models.CharField(blank=True, default='/static/audio/alarm_perso.mp3', max_length=255, verbose_name='Son alerte personnalisée'),
        ),
    ]
