# Generated by ChatGPT on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couveuse_app', '0008_alter_parametre_son_j_1_alter_parametre_son_j_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='Chat ID Telegram du client, facultatif', max_length=50, verbose_name='Chat ID Telegram'),
        ),
    ]
